name: Quasar Build and Run

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Quasar app
        run: npm run build

  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Quasar app
        run: npm run dev
